global:
  cluster: "irp2-eks-main-blue-ng"

agent-eval:
  ingress:
    annotations:
      alb.ingress.kubernetes.io/load-balancer-name: "irp2-agent-evaluation-alb-blue-ng"
      external-dns.alpha.kubernetes.io/hostname: "agent-evaluation-blue-ng.irp2.ovp.kaltura.prod"
