global:
  environment: nvq2
  stage: qa
  image:
    repository: "383697330906.dkr.ecr.us-east-1.amazonaws.com"
template:
  enabled: true
  annotations:
    kaltura.com/observability: apps
    prometheus.io/path: /metrics
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'
    vector.dev/logziobackend: 'true'
    vector.dev/s3: 'true'
  containers:
    template:
      image:
        registry: template
        tag: "9fbf7dd"
      environmentVariables:
        - name: ENV_NAME
          value: "nvq2"
        - name: KALTURA_API_ENDPOINT
          value: "http://front-api.nvq2.ovp.kaltura.prod"
  ingress:
    annotations:
      alb.ingress.kubernetes.io/subnets: "subnet-0d0248bf16e6e7e3d,subnet-04bdbf232432ee2f8,subnet-007f81aa04b67b9ff,subnet-063f6cb2f23edbe5a,subnet-0f0a1c0b4cee481c3"
    spec:
      rules:
        - http:
            paths:
              - path: /*
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: nvq2-ovp-ms-template-template-http-service
                    port:
                      number: 80
  kedaHpa:
    template:
      minReplicaCount: 1
      maxReplicaCount: 1
      target:
        name: nvq2-ovp-ms-template-template
      hpaScaler:
        triggers:
          - type: cpu
            metadata:
              type: Utilization
              value: "60"
          - type: memory
            metadata:
              type: Utilization
              value: "60"
