{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agent-evaluation-agent-eval-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: agent-evaluation-agent-eval-secrets
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: /{{ .Values.global.environment }}/agent-evaluation/agent-eval-secrets
  refreshInterval: 5m
{{- else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: agent-evaluation-agent-eval-secrets
data: {}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: agent-evaluation-agent-eval-env-vars
data:
  {{- range $key, $value := .Values.environments }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
