# Store here values for your ephemeral environment
# If you don't know what I'm talking about, refer to our documentation:
# https://kaltura.atlassian.net/wiki/spaces/CP/pages/4922901748/Ephemeral+environments+-+Onboarding+new+repository

