global:
  environment: irp2
  stage: prod
  image:
    repository: "137576761235.dkr.ecr.eu-west-1.amazonaws.com"

agent-eval:
  enabled: false
  annotations:
    kaltura.com/observability: apps
    prometheus.io/path: /metrics
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'
    vector.dev/logziobackend: 'true'
    vector.dev/s3: 'true'
  containers:
    agent-eval:
      image:
        registry: agent-eval
        tag: "latest"
      environmentVariables:
        - name: ENV_NAME
          value: "irp2"
        - name: KALTURA_API_ENDPOINT
          value: "http://front-api.irp2.ovp.kaltura.prod"
  ingress:
    annotations:
      alb.ingress.kubernetes.io/subnets: "subnet-06b0b7b1f5d70d5f4,subnet-0e1eac32941635b5f,subnet-0ca2752ed636c4a3a"
    spec:
      rules:
        - http:
            paths:
              - path: /*
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: irp2-agent-evaluation-agent-eval-http-service
                    port:
                      number: 80
  kedaHpa:
    agent-eval:
      minReplicaCount: 2
      maxReplicaCount: 20
      target:
        name: irp2-agent-evaluation-agent-eval
      hpaScaler:
        triggers:
          - type: cpu
            metadata:
              type: Utilization
              value: "70"
          - type: memory
            metadata:
              type: Utilization
              value: "70"
