global:
  cluster: "nvp1-eks-main-blue-ng"

template:
  ingress:
    annotations:
      alb.ingress.kubernetes.io/load-balancer-name: "nvp1-ovp-ms-template-alb-blue-ng"
      external-dns.alpha.kubernetes.io/hostname: "ovp-ms-template-blue-ng.nvp1.ovp.kaltura.prod"
