openapi: 3.0.0
paths:
  /api/v1/template/create:
    post:
      operationId: create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTemplateDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
      security:
        - ks: []
      summary: create template
      tags: &a1
        - template
  /api/v1/template/pingKalturaExample:
    post:
      operationId: pingKalturaExample
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: boolean
      security:
        - ks: []
      summary: Example usage of Kaltura client
      tags: *a1
  /metrics:
    get:
      operationId: index
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - Prometheus
info:
  title: template
  description: ""
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    ks:
      scheme: bearer
      bearerFormat: KS
      type: http
  schemas:
    CreateTemplateDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
